const fs = require('fs');
const path = require('path');

/**
 * Load .env file and write a generated __env__.ts that gets bundled.
 * This is the most reliable env injection approach for React Native CLI.
 */
function loadEnv() {
  const envPath = path.resolve(__dirname, '.env');
  const env = {};
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const idx = trimmed.indexOf('=');
      if (idx < 0) continue;
      const key = trimmed.slice(0, idx).trim();
      const val = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
      env[key] = val;
    }
  }
  for (const key of ENV_KEYS) {
    if (process.env[key] !== undefined) {
      env[key] = process.env[key];
    }
  }
  return env;
}

const ENV_KEYS = [
  'TBOT_API_URL',
  'TBOT_AI_URL',
  'EXPO_PUBLIC_API_BASE_URL',
  'EXPO_PUBLIC_GEMINI_LIVE_MODEL',
  'EXPO_PUBLIC_SENTRY_DSN',
  'EXPO_PUBLIC_POSTHOG_API_KEY',
  'EXPO_PUBLIC_POSTHOG_HOST',
  'EXPO_PUBLIC_VOICE_BARGE_IN_BUDGET_MS',
  'EXPO_PUBLIC_VOICE_TEST_HARNESS',
  'EXPO_PUBLIC_VOICE_CANCEL_UNACK_RECOVERY',
];

const env = loadEnv();
const apiUrl = env.TBOT_API_URL || env.EXPO_PUBLIC_API_BASE_URL || '';

function sanitizedAiUrl(value) {
  const trimmed = (value || '').replace(/\/+$/, '');
  if (trimmed === 'http://localhost:3001/api/ai' || trimmed === 'http://127.0.0.1:3001/api/ai') {
    return '';
  }
  return value || '';
}

// Write src/__env__.ts so it can be imported by src/config.ts.
// Keep this allowlist in sync with every ENV.<KEY> access in src/config.ts —
// a missing key here surfaces as a TS2339 "Property does not exist" error
// at build time (caught by `npx tsc --noEmit`).
const envTs = `// AUTO-GENERATED by metro.config.js — do not edit manually
export const ENV = {
  TBOT_API_URL: ${JSON.stringify(apiUrl)},
  TBOT_AI_URL: ${JSON.stringify(sanitizedAiUrl(env.TBOT_AI_URL))},
  EXPO_PUBLIC_GEMINI_LIVE_MODEL: ${JSON.stringify(env.EXPO_PUBLIC_GEMINI_LIVE_MODEL || '')},
  EXPO_PUBLIC_SENTRY_DSN: ${JSON.stringify(env.EXPO_PUBLIC_SENTRY_DSN || '')},
  EXPO_PUBLIC_POSTHOG_API_KEY: ${JSON.stringify(env.EXPO_PUBLIC_POSTHOG_API_KEY || '')},
  EXPO_PUBLIC_POSTHOG_HOST: ${JSON.stringify(env.EXPO_PUBLIC_POSTHOG_HOST || '')},
  EXPO_PUBLIC_VOICE_BARGE_IN_BUDGET_MS: ${JSON.stringify(env.EXPO_PUBLIC_VOICE_BARGE_IN_BUDGET_MS || '')},
  EXPO_PUBLIC_VOICE_TEST_HARNESS: ${JSON.stringify(env.EXPO_PUBLIC_VOICE_TEST_HARNESS || '')},
  EXPO_PUBLIC_VOICE_CANCEL_UNACK_RECOVERY: ${JSON.stringify(env.EXPO_PUBLIC_VOICE_CANCEL_UNACK_RECOVERY || '')},
};
`;
const envTsPath = path.resolve(__dirname, 'src/__env__.ts');
fs.writeFileSync(envTsPath, envTs);

if (apiUrl || env.TBOT_AI_URL || env.EXPO_PUBLIC_GEMINI_LIVE_MODEL) {
  console.log('[metro] Injecting env vars from .env:');
  if (apiUrl) console.log(`  TBOT_API_URL = ${apiUrl}`);
  if (env.TBOT_AI_URL) console.log(`  TBOT_AI_URL  = ${env.TBOT_AI_URL}`);
  if (env.EXPO_PUBLIC_GEMINI_LIVE_MODEL) console.log(`  EXPO_PUBLIC_GEMINI_LIVE_MODEL = ${env.EXPO_PUBLIC_GEMINI_LIVE_MODEL}`);
}

/**
 * Metro configuration — Expo SDK 55
 * Uses expo/metro-config for correct Hermes support.
 *
 * Note: expo/virtual/streams.js has been removed from the polyfills list in
 * node_modules/@expo/cli/.../withMetroMultiPlatform.js because Metro's Babel
 * transform converts its inline UMD helpers to require() calls, crashing Hermes
 * before the module registry is ready. RN 0.83 + Hermes provides streams natively.
 */
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Support @google/genai/web which uses "module" field and .mjs files
config.resolver.sourceExts = [...(config.resolver.sourceExts || []), 'mjs'];
config.resolver.resolverMainFields = ['react-native', 'module', 'main'];

module.exports = config;
