const fs = require('fs');
const path = require('path');

/**
 * Load .env and write a generated __env__.ts that gets bundled.
 * Only EXPO_PUBLIC_* keys are allowlisted; non-prefixed values are never
 * embedded so they cannot leak into cached or release artifacts.
 */
function loadEnv() {
  const envPath = path.resolve(__dirname, '.env');
  if (!fs.existsSync(envPath)) return {};
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx < 0) continue;
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
    env[key] = val;
  }
  return env;
}

const env = loadEnv();

// Only EXPO_PUBLIC_* values may be baked into the bundle. Keep this list in
// sync with every ENV.<KEY> access in src/ so missing keys surface as a
// TS2339 error at `npx tsc --noEmit` time.
const EXPO_PUBLIC_ALLOWLIST = [
  'EXPO_PUBLIC_TBOT_API_URL',
  'EXPO_PUBLIC_TBOT_AI_URL',
  'EXPO_PUBLIC_WS_URL',
  'EXPO_PUBLIC_GEMINI_LIVE_MODEL',
  'EXPO_PUBLIC_SENTRY_DSN',
  'EXPO_PUBLIC_POSTHOG_API_KEY',
  'EXPO_PUBLIC_POSTHOG_HOST',
  'EXPO_PUBLIC_VOICE_BARGE_IN_BUDGET_MS',
  'EXPO_PUBLIC_VOICE_TEST_HARNESS',
  'EXPO_PUBLIC_VOICE_CANCEL_UNACK_RECOVERY',
  'EXPO_PUBLIC_ESP_DEVICE_PREFIX',
  'EXPO_PUBLIC_ESP_SECURITY',
];

const envTs = `// AUTO-GENERATED by metro.config.js — do not edit manually
export const ENV = {
${EXPO_PUBLIC_ALLOWLIST.map((key) => `  ${key}: ${JSON.stringify(env[key] || '')},`).join('\n')}
};
`;
const envTsPath = path.resolve(__dirname, 'src/__env__.ts');
fs.writeFileSync(envTsPath, envTs);
const injected = EXPO_PUBLIC_ALLOWLIST.filter((key) => env[key]);
if (injected.length) {
  console.info('[metro] Injecting EXPO_PUBLIC_* env vars from .env:');
  for (const key of injected) {
    console.info(`  ${key} = ${env[key]}`);
  }
}

/**
 * Metro configuration — Expo SDK 55
 * Uses expo/metro-config for correct Hermes support.
 *
 * Note: expo/virtual/streams.js has been removed from the polyfills list in
 * node_modules/@expo/cli/.../withMetroMultiPlatform.js because Metro's Babel
 * transform converts its inline UMD helpers to require() calls, crashing Hermes
 * before the module registry is ready. RN 0.83 + Hermes provides streams natively.
 */
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Support @google/genai/web which uses "module" field and .mjs files
config.resolver.sourceExts = [...(config.resolver.sourceExts || []), 'mjs'];
config.resolver.resolverMainFields = ['react-native', 'module', 'main'];

module.exports = config;
