const fs = require('fs');
const path = require('path');

/**
 * Load .env file and write a generated __env__.ts that gets bundled.
 * This is the most reliable env injection approach for React Native CLI.
 */
function loadEnv() {
  const envPath = path.resolve(__dirname, '.env');
  if (!fs.existsSync(envPath)) return {};
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx < 0) continue;
    const key = trimmed.slice(0, idx).trim();
    const val = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
    env[key] = val;
  }
  return env;
}

const env = loadEnv();

// Write src/__env__.ts so it can be imported by src/config.ts
const envTs = `// AUTO-GENERATED by metro.config.js — do not edit manually
export const ENV = {
  TBOT_API_URL: ${JSON.stringify(env.TBOT_API_URL || '')},
  TBOT_AI_URL: ${JSON.stringify(env.TBOT_AI_URL || '')},
};
`;
const envTsPath = path.resolve(__dirname, 'src/__env__.ts');
fs.writeFileSync(envTsPath, envTs);

if (env.TBOT_API_URL || env.TBOT_AI_URL) {
  console.log('[metro] Injecting env vars from .env:');
  if (env.TBOT_API_URL) console.log(`  TBOT_API_URL = ${env.TBOT_API_URL}`);
  if (env.TBOT_AI_URL) console.log(`  TBOT_AI_URL  = ${env.TBOT_AI_URL}`);
}

/**
 * Metro configuration — Expo SDK 55
 * Uses expo/metro-config for correct Hermes support.
 *
 * Note: expo/virtual/streams.js has been removed from the polyfills list in
 * node_modules/@expo/cli/.../withMetroMultiPlatform.js because Metro's Babel
 * transform converts its inline UMD helpers to require() calls, crashing Hermes
 * before the module registry is ready. RN 0.83 + Hermes provides streams natively.
 */
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

module.exports = config;
