/**
 * JSON sidecar schema for the VAD calibration corpus.
 *
 * Every audio sample in tests/audio/vad-corpus/{child,adult,ambient,mixed}/
 * must have a companion JSON file with the same base name (e.g.
 * child_001.wav → child_001.json) that conforms to VadSampleSidecar.
 *
 * The sidecar is generated by record.sh at capture time and enriched by
 * label.html when a human adds onset/offset markers.
 *
 * calibrate.ts reads these sidecars to compute VAD parameter grids.
 */

export type VadCategory = 'child' | 'adult' | 'ambient' | 'mixed';

/**
 * Label state set by label.html after a human review pass.
 * 'unlabeled'  — sidecar generated by record.sh; onset/offset not yet marked.
 * 'labeled'    — onset/offset present; calibrate.ts treats as ground truth.
 * 'rejected'   — sample has quality issues (clipping, background noise spike);
 *                calibrate.ts skips these.
 */
export type VadLabelState = 'unlabeled' | 'labeled' | 'rejected';

/**
 * A single marker placed by label.html on the waveform.
 * Times are in seconds, relative to the start of the file (t=0).
 */
export interface VadSpeechMarker {
  readonly onsetSec: number;   // first frame considered speech
  readonly offsetSec: number;  // first frame after speech ends
  readonly confidence: 'high' | 'medium' | 'low';
  readonly notes: string;      // free-text reviewer comment
}

/**
 * Canonical sidecar shape. Every field except markers/labelState is written
 * by record.sh. label.html fills markers and updates labelState.
 */
export interface VadSampleSidecar {
  /** ISO-8601 capture timestamp (UTC) written by record.sh. */
  readonly capturedAt: string;
  /** Category sub-directory this sample belongs to. */
  readonly category: VadCategory;
  /** Monotonic index within category (1-based). */
  readonly index: number;
  /** Base filename of the corresponding WAV (no path, no extension). */
  readonly baseName: string;
  /** Sample rate of the WAV in Hz — must be 16000. */
  readonly sampleRateHz: 16000;
  /** Number of channels — must be 1 (mono). */
  readonly channels: 1;
  /** Bit depth — must be 16 (Int16 PCM). */
  readonly bitDepth: 16;
  /** Actual duration of the WAV in seconds (measured at record time). */
  readonly durationSec: number;
  /** Recording environment description (free text). */
  readonly environment: string;
  /** Speaker age group for child/adult/mixed categories; null for ambient. */
  readonly speakerAgeGroup: 'child' | 'adult' | null;
  /**
   * Whether the recording contains speech.
   * true  — child/adult/mixed samples.
   * false — ambient samples (background noise only).
   */
  readonly containsSpeech: boolean;
  /** Labeling state; written by record.sh as 'unlabeled'. */
  labelState: VadLabelState;
  /**
   * Speech onset/offset markers placed by the human labeler.
   * Empty array until labelState === 'labeled'.
   * Ambient samples that are correctly silent may have an empty array even
   * when labeled (they contain no speech segments by definition).
   */
  markers: readonly VadSpeechMarker[];
  /** label.html writes the ISO-8601 timestamp when it saves changes. */
  labeledAt: string | null;
  /** record.sh writes its own semver for forward-compat schema checks. */
  readonly schemaVersion: '1.0';
}

/**
 * Shape of calibration-result.json produced by calibrate.ts.
 */
export interface VadCalibrationResult {
  readonly producedAt: string;
  readonly corpusSummary: {
    readonly total: number;
    readonly labeled: number;
    readonly skipped: number;
    readonly byCategory: Record<VadCategory, number>;
  };
  readonly bestParams: {
    readonly eThresholdDb: number;
    readonly zcrLow: number;
    readonly zcrHigh: number;
    readonly hangoverMs: number;
  };
  readonly bestScore: number;         // TPR - FPR on the labeled subset
  readonly truePositiveRate: number;
  readonly falsePositiveRate: number;
  readonly gridSearchSteps: number;
  readonly planDefaults: {
    readonly eThresholdDb: -42;
    readonly zcrLow: 0.05;
    readonly zcrHigh: 0.45;
    readonly hangoverMs: 400;
  };
}
