#!/usr/bin/env node
// build-index.mjs — emit docs/sequences/README.md grouped by system, with surface + externals columns.
//
// Sort key (per plan §6 + AC-8): alpha by `system` then `flow_id`.
//
// Flags:
//   --check   Compare generated content against committed README.md; non-zero on diff.
//
// Pure ESM, no deps. Reuses parse-frontmatter.

import fs from 'node:fs';
import path from 'node:path';
import { readFrontmatter } from './lib/parse-frontmatter.mjs';
import { DOCS_ROOT } from '../_lib/paths.mjs';

const SEQ_DIR = path.join(DOCS_ROOT, 'sequences');
const README_PATH = path.join(SEQ_DIR, 'README.md');

const CHECK_MODE = process.argv.includes('--check');

function walk(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) out.push(...walk(p));
    else if (ent.isFile() && p.endsWith('.sequence.mmd')) out.push(p);
  }
  return out;
}

function loadAll() {
  const rows = [];
  for (const p of walk(SEQ_DIR)) {
    let fm;
    try { fm = readFrontmatter(p).data; } catch { continue; }
    const rel = path.relative(SEQ_DIR, p).split(path.sep).join('/');
    rows.push({
      file: rel,
      system: String(fm.system || ''),
      flow_id: String(fm.flow_id || ''),
      surface: String(fm.surface || ''),
      externals: Array.isArray(fm.externals) ? fm.externals : [],
      status: String(fm.status || ''),
    });
  }
  rows.sort((a, b) => a.system.localeCompare(b.system) || a.flow_id.localeCompare(b.flow_id));
  return rows;
}

function render(rows) {
  const lines = [];
  lines.push('<!-- GENERATED by scripts/sequences/build-index.mjs. Do not edit by hand. -->');
  lines.push('');
  lines.push('# Backend Sequence Diagrams — Index');
  lines.push('');
  lines.push('Hand-authored + spec-seeded `sequenceDiagram` files covering all 22 backend systems at **contract-level** depth.');
  lines.push('Distinct from `docs/flows/` (mobile UI nav-graph). See `AGENTS.md` for ownership lanes and `_actors.md` for the participant allow-list.');
  lines.push('');
  lines.push(`Total files: **${rows.length}**.`);
  lines.push('');

  // Group by system.
  const bySystem = new Map();
  for (const r of rows) {
    if (!bySystem.has(r.system)) bySystem.set(r.system, []);
    bySystem.get(r.system).push(r);
  }
  for (const system of [...bySystem.keys()].sort()) {
    lines.push(`## ${system}`);
    lines.push('');
    lines.push('| flow_id | surface | externals | status | file |');
    lines.push('|---|---|---|---|---|');
    for (const r of bySystem.get(system)) {
      const ext = r.externals.length ? r.externals.join(', ') : '—';
      lines.push(`| ${r.flow_id} | ${r.surface} | ${ext} | ${r.status} | \`${r.file}\` |`);
    }
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

const rendered = render(loadAll());

if (CHECK_MODE) {
  const committed = fs.existsSync(README_PATH) ? fs.readFileSync(README_PATH, 'utf8') : '';
  if (committed !== rendered) {
    console.error('[build-index] FAIL: docs/sequences/README.md is stale. Run `npm run sequences:index` to regenerate.');
    process.exit(1);
  }
  console.log('[build-index] README.md is up to date.');
} else {
  fs.writeFileSync(README_PATH, rendered);
  console.log(`[build-index] wrote docs/sequences/README.md (${rendered.length} bytes)`);
}
