import { StyleSheet } from 'react-native';
import { referenceColors } from '@/design-system/referenceTheme';

export const COLORS = {
  background: referenceColors.bg,
  card: '#FFFFFF',
  ink: '#2D3436',
  muted: '#636E72',
  border: '#EBDCC7',
  primary: '#FF6B6B',
  primarySoft: '#FFF4F2',
  secondary: '#4ECDC4',
  success: '#2BAF8D',
  white: '#FFFFFF',
} as const;

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  authContent: {
    flexGrow: 1,
    paddingTop: 8,
  },
  authHeader: {
    height: 52,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  roundBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  headerSpacer: {
    width: 40,
  },
  authHeaderTitle: {
    color: COLORS.ink,
    fontSize: 18,
    lineHeight: 23,
  },
  authHero: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 26,
  },
  authTitle: {
    color: COLORS.ink,
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.4,
    textAlign: 'center',
    marginTop: 2,
    marginBottom: 4,
  },
  authSubtitle: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  authSheet: {
    flexGrow: 1,
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 48,
    borderTopRightRadius: 48,
    paddingHorizontal: 30,
    paddingTop: 12,
    paddingBottom: 34,
    shadowColor: '#164E63',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 8,
  },
  modeTabs: {
    flexDirection: 'row',
    borderRadius: 20,
    backgroundColor: '#F5ECDD',
    padding: 4,
    marginBottom: 24,
  },
  modeTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 46,
    borderRadius: 16,
    paddingHorizontal: 12,
  },
  modeTabActive: {
    backgroundColor: COLORS.white,
    shadowColor: COLORS.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  modeTabText: {
    color: COLORS.muted,
    fontSize: 15,
    lineHeight: 20,
  },
  modeTabTextActive: {
    color: COLORS.primary,
  },
  formFields: {
    gap: 16,
  },
  fieldGroup: {
    gap: 7,
  },
  formLabel: {
    color: COLORS.ink,
    fontSize: 14,
    lineHeight: 18,
  },
  formInput: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(235,220,199,0.7)',
    backgroundColor: COLORS.background,
    color: COLORS.ink,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: '600',
  },
  passwordWrap: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(235,220,199,0.7)',
    backgroundColor: COLORS.background,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
  },
  passwordInput: {
    flex: 1,
    color: COLORS.ink,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: '600',
  },
  eyeButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputInvalid: {
    borderColor: COLORS.primary,
    borderWidth: 2,
  },
  fieldError: {
    color: COLORS.primary,
    fontSize: 12,
    lineHeight: 17,
  },
  centerError: {
    color: COLORS.primary,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 12,
  },
  centerSuccess: {
    color: COLORS.success,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginBottom: 14,
  },
  inlineForgotButton: {
    alignSelf: 'flex-end',
    marginTop: 14,
  },
  inlineForgotText: {
    color: COLORS.primary,
    fontSize: 13,
    lineHeight: 18,
  },
  sheetPrimaryButton: {
    minHeight: 62,
    borderRadius: 31,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 17,
    marginTop: 24,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    elevation: 4,
  },
  primaryButton: {
    width: '100%',
    minHeight: 68,
    borderRadius: 34,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 19,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.24,
    shadowRadius: 15,
    elevation: 5,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontSize: 20,
    lineHeight: 25,
    textAlign: 'center',
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  switchPrompt: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  switchPromptText: {
    color: COLORS.muted,
    fontSize: 13,
  },
  switchPromptLink: {
    color: COLORS.primary,
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  legal: {
    color: COLORS.muted,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
    marginTop: 4,
  },
  legalLink: {
    color: COLORS.primary,
  },
  errorContent: {
    flexGrow: 1,
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 42,
    alignItems: 'center',
  },
  decorCircleTop: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(255,255,255,0.26)',
    top: -110,
    right: -100,
  },
  errorHero: {
    height: 188,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTitle: {
    color: COLORS.ink,
    fontSize: 24,
    lineHeight: 31,
    textAlign: 'center',
    maxWidth: 330,
    marginBottom: 28,
  },
  errorCard: {
    width: '100%',
    backgroundColor: COLORS.primarySoft,
    borderWidth: 2,
    borderColor: 'rgba(255,107,107,0.2)',
    borderRadius: 34,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 24,
  },
  alertIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,107,107,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorCardCopy: {
    flex: 1,
    paddingTop: 2,
  },
  errorCardTitle: {
    color: COLORS.primary,
    fontSize: 15,
    lineHeight: 20,
    marginBottom: 3,
  },
  errorCardBody: {
    color: 'rgba(255,107,107,0.75)',
    fontSize: 13,
    lineHeight: 18,
  },
  errorFields: {
    width: '100%',
    gap: 18,
    marginBottom: 26,
  },
  errorLabel: {
    color: COLORS.muted,
    fontSize: 11,
    lineHeight: 15,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginLeft: 18,
  },
  errorInput: {
    width: '100%',
    minHeight: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'rgba(235,220,199,0.45)',
    backgroundColor: COLORS.white,
    color: COLORS.ink,
    paddingHorizontal: 24,
    paddingVertical: 16,
    fontSize: 15,
    fontWeight: '600',
    shadowColor: '#164E63',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  recoverButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  recoverPrompt: {
    color: COLORS.muted,
    fontSize: 13,
  },
  recoverLink: {
    color: COLORS.primary,
    fontSize: 13,
  },
  forgotContent: {
    flexGrow: 1,
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 42,
    alignItems: 'center',
  },
  squareBackButton: {
    position: 'absolute',
    top: 18,
    left: 24,
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(235,220,199,0.35)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
    zIndex: 2,
  },
  forgotHero: {
    height: 210,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  forgotTitle: {
    color: COLORS.ink,
    fontSize: 34,
    lineHeight: 40,
    letterSpacing: -0.6,
    textAlign: 'center',
    maxWidth: 340,
    marginBottom: 12,
  },
  forgotSubtitle: {
    color: COLORS.muted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    maxWidth: 330,
    marginBottom: 34,
  },
  forgotForm: {
    width: '100%',
    gap: 8,
    marginBottom: 26,
  },
  emailIconWrap: {
    width: '100%',
    minHeight: 66,
    borderRadius: 33,
    borderWidth: 2,
    borderColor: 'rgba(235,220,199,0.5)',
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 24,
    paddingRight: 12,
    shadowColor: '#164E63',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  emailIconInput: {
    flex: 1,
    color: COLORS.ink,
    paddingHorizontal: 16,
    paddingVertical: 17,
    fontSize: 15,
    fontWeight: '600',
  },
  resendButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 18,
  },
  resendText: {
    color: COLORS.primary,
    fontSize: 13,
    lineHeight: 18,
  },
});
