appId: net.jasonle.tjbot
name: Assert ParentSettingsScreen
---
- runFlow:
    when:
      visible: "Open"
    commands:
      - tapOn: "Open"
- extendedWaitUntil:
    visible:
      text: ".*(Settings|Cài đặt).*"
    timeout: 15000
- runFlow:
    when:
      visible: ".*(App language|Ngôn ngữ).*"
    commands:
      - tapOn: ".*(App language|Ngôn ngữ).*"
- back
- waitForAnimationToEnd
