import type { ImageSourcePropType } from 'react-native';

/** Transparent derivatives of the locked legacy greet loop, sampled at 77 frames. */
export const GREET_FRAME_COUNT = 77;
export const GREET_LOOP_MS = 9540;

export const GREET_FRAMES: ImageSourcePropType[] = [
  require('./frame-001.png'),
  require('./frame-004.png'),
  require('./frame-007.png'),
  require('./frame-010.png'),
  require('./frame-013.png'),
  require('./frame-016.png'),
  require('./frame-019.png'),
  require('./frame-022.png'),
  require('./frame-025.png'),
  require('./frame-028.png'),
  require('./frame-031.png'),
  require('./frame-034.png'),
  require('./frame-037.png'),
  require('./frame-040.png'),
  require('./frame-043.png'),
  require('./frame-046.png'),
  require('./frame-049.png'),
  require('./frame-052.png'),
  require('./frame-055.png'),
  require('./frame-058.png'),
  require('./frame-061.png'),
  require('./frame-064.png'),
  require('./frame-067.png'),
  require('./frame-070.png'),
  require('./frame-073.png'),
  require('./frame-076.png'),
  require('./frame-079.png'),
  require('./frame-082.png'),
  require('./frame-085.png'),
  require('./frame-088.png'),
  require('./frame-091.png'),
  require('./frame-094.png'),
  require('./frame-097.png'),
  require('./frame-100.png'),
  require('./frame-103.png'),
  require('./frame-106.png'),
  require('./frame-109.png'),
  require('./frame-112.png'),
  require('./frame-115.png'),
  require('./frame-118.png'),
  require('./frame-121.png'),
  require('./frame-124.png'),
  require('./frame-127.png'),
  require('./frame-130.png'),
  require('./frame-133.png'),
  require('./frame-136.png'),
  require('./frame-139.png'),
  require('./frame-142.png'),
  require('./frame-145.png'),
  require('./frame-148.png'),
  require('./frame-151.png'),
  require('./frame-154.png'),
  require('./frame-157.png'),
  require('./frame-160.png'),
  require('./frame-163.png'),
  require('./frame-166.png'),
  require('./frame-169.png'),
  require('./frame-172.png'),
  require('./frame-175.png'),
  require('./frame-178.png'),
  require('./frame-181.png'),
  require('./frame-184.png'),
  require('./frame-187.png'),
  require('./frame-190.png'),
  require('./frame-193.png'),
  require('./frame-196.png'),
  require('./frame-199.png'),
  require('./frame-202.png'),
  require('./frame-205.png'),
  require('./frame-208.png'),
  require('./frame-211.png'),
  require('./frame-214.png'),
  require('./frame-217.png'),
  require('./frame-220.png'),
  require('./frame-223.png'),
  require('./frame-226.png'),
  require('./frame-229.png'),
];

export default GREET_FRAMES;
