export const STATES = [
  { id: 'dv_overview',          title: 'Rotjtjbot · How it works together',  group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_add',          title: 'Rotjtjbot · Pair · add',             group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_intro',        title: 'Rotjtjbot · Pair · turn on',         group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_search',       title: 'Rotjtjbot · Pair · searching',       group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_found',        title: 'Rotjtjbot · Pair · found',           group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_code',         title: 'Rotjtjbot · Pair · confirm code',    group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_wifi',         title: 'Rotjtjbot · Pair · Wi-Fi pick',      group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_wifi_pw',      title: 'Rotjtjbot · Pair · Wi-Fi password',  group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_connecting',   title: 'Rotjtjbot · Pair · connecting',      group: 'Rotjtjbot Device', kind: 'edge' },
  { id: 'dv_pair_success',      title: 'Rotjtjbot · Pair · success',         group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_failed',       title: 'Rotjtjbot · Pair · failed',          group: 'Rotjtjbot Device', kind: 'edge' },
  { id: 'dv_pair_offline',      title: 'Rotjtjbot · Pair · offline',         group: 'Rotjtjbot Device', kind: 'edge' },
  { id: 'dv_pair_rename',       title: 'Rotjtjbot · Pair · rename & buddy',  group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_pair_first_lesson', title: 'Rotjtjbot · Pair · first lesson',    group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_home',              title: 'Rotjtjbot · Device home',            group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_session',           title: 'Rotjtjbot · Live session monitor',   group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_lost',              title: 'Rotjtjbot · Find my Rotjtjbot',          group: 'Rotjtjbot Device', kind: 'edge' },
  { id: 'dv_firmware',          title: 'Rotjtjbot · Firmware update',        group: 'Rotjtjbot Device', kind: 'edge' },
  { id: 'dv_lcd',               title: 'Rotjtjbot · LCD face library',       group: 'Rotjtjbot Device', kind: 'happy' },
  { id: 'dv_lcd_turn',          title: 'Rotjtjbot · LCD lesson turn',        group: 'Rotjtjbot Device', kind: 'happy' },
] as const;
