export const STATES = [
  { id:'dv_overview',          title:'Robot · How it works together',  group:'Robot Device', kind:'happy' },
  { id:'dv_pair_add',          title:'Robot · Pair · add',             group:'Robot Device', kind:'happy' },
  { id:'dv_pair_intro',        title:'Robot · Pair · turn on',         group:'Robot Device', kind:'happy' },
  { id:'dv_pair_search',       title:'Robot · Pair · searching',       group:'Robot Device', kind:'happy' },
  { id:'dv_pair_found',        title:'Robot · Pair · found',           group:'Robot Device', kind:'happy' },
  { id:'dv_pair_code',         title:'Robot · Pair · confirm code',    group:'Robot Device', kind:'happy' },
  { id:'dv_pair_wifi',         title:'Robot · Pair · Wi-Fi pick',      group:'Robot Device', kind:'happy' },
  { id:'dv_pair_wifi_pw',      title:'Robot · Pair · Wi-Fi password',  group:'Robot Device', kind:'happy' },
  { id:'dv_pair_connecting',   title:'Robot · Pair · connecting',      group:'Robot Device', kind:'edge'  },
  { id:'dv_pair_success',      title:'Robot · Pair · success',         group:'Robot Device', kind:'happy' },
  { id:'dv_pair_failed',       title:'Robot · Pair · failed',          group:'Robot Device', kind:'edge'  },
  { id:'dv_pair_offline',      title:'Robot · Pair · offline',         group:'Robot Device', kind:'edge'  },
  { id:'dv_pair_rename',       title:'Robot · Pair · rename & buddy',  group:'Robot Device', kind:'happy' },
  { id:'dv_pair_first_lesson', title:'Robot · Pair · first lesson',    group:'Robot Device', kind:'happy' },
  { id:'dv_home',              title:'Robot · Device home',            group:'Robot Device', kind:'happy' },
  { id:'dv_session',           title:'Robot · Live session monitor',   group:'Robot Device', kind:'happy' },
  { id:'dv_lost',              title:'Robot · Find my Robot',          group:'Robot Device', kind:'edge'  },
  { id:'dv_firmware',          title:'Robot · Firmware update',        group:'Robot Device', kind:'edge'  },
  { id:'dv_lcd',               title:'Robot · LCD face library',       group:'Robot Device', kind:'happy' },
  { id:'dv_lcd_turn',          title:'Robot · One lesson turn',        group:'Robot Device', kind:'happy' },
];
