// AUTO-GENERATED by metro.config.js — do not edit manually
export const ENV = {
  TBOT_API_URL: "http://tbot-staging-alb-81759857.ap-southeast-1.elb.amazonaws.com/v1",
  TBOT_AI_URL: "http://tbot-staging-alb-81759857.ap-southeast-1.elb.amazonaws.com/api/ai",
};
