// AUTO-GENERATED by metro.config.js — do not edit manually
export const ENV = {
  TBOT_API_URL: "https://tbot-backend-8wmh.onrender.com",
  TBOT_AI_URL: "https://tbot-backend-8wmh.onrender.com/api/ai",
  EXPO_PUBLIC_GEMINI_LIVE_MODEL: "",
  EXPO_PUBLIC_SENTRY_DSN: "",
  EXPO_PUBLIC_POSTHOG_API_KEY: "",
  EXPO_PUBLIC_POSTHOG_HOST: "",
  EXPO_PUBLIC_VOICE_FORCE_NATIVE_IOS: "true",
};
