// Secret-free template for clean checkouts and CI. Expo replaces
// EXPO_PUBLIC_* references at bundle time; local values remain in .env.
export const ENV = {
  EXPO_PUBLIC_TBOT_API_URL: process.env.EXPO_PUBLIC_TBOT_API_URL,
  EXPO_PUBLIC_TBOT_AI_URL: process.env.EXPO_PUBLIC_TBOT_AI_URL,
  EXPO_PUBLIC_WS_URL: process.env.EXPO_PUBLIC_WS_URL,
  TBOT_API_URL: process.env.EXPO_PUBLIC_TBOT_API_URL,
  TBOT_AI_URL: process.env.EXPO_PUBLIC_TBOT_AI_URL,
  EXPO_PUBLIC_GEMINI_LIVE_MODEL: process.env.EXPO_PUBLIC_GEMINI_LIVE_MODEL,
  EXPO_PUBLIC_GEMINI_DEMO_API_KEY: process.env.EXPO_PUBLIC_GEMINI_DEMO_API_KEY,
  EXPO_PUBLIC_SENTRY_DSN: process.env.EXPO_PUBLIC_SENTRY_DSN,
  EXPO_PUBLIC_POSTHOG_API_KEY: process.env.EXPO_PUBLIC_POSTHOG_API_KEY,
  EXPO_PUBLIC_POSTHOG_HOST: process.env.EXPO_PUBLIC_POSTHOG_HOST,
  EXPO_PUBLIC_VOICE_BARGE_IN_BUDGET_MS:
    process.env.EXPO_PUBLIC_VOICE_BARGE_IN_BUDGET_MS,
  EXPO_PUBLIC_VOICE_TEST_HARNESS:
    process.env.EXPO_PUBLIC_VOICE_TEST_HARNESS,
  EXPO_PUBLIC_VOICE_CANCEL_UNACK_RECOVERY:
    process.env.EXPO_PUBLIC_VOICE_CANCEL_UNACK_RECOVERY,
  EXPO_PUBLIC_ESP_DEVICE_PREFIX: process.env.EXPO_PUBLIC_ESP_DEVICE_PREFIX,
  EXPO_PUBLIC_ESP_SECURITY: process.env.EXPO_PUBLIC_ESP_SECURITY,
  EXPO_PUBLIC_INVESTOR_DEMO: process.env.EXPO_PUBLIC_INVESTOR_DEMO,
} as const;
