-keep class com.TJBotmobile.MainApplication { *; }
-keep class com.TJBotmobile.MainActivity { *; }
-keep class androidx.core.app.CoreComponentFactory { *; }
-keep class com.facebook.react.ReactApplication { *; }
-keep class com.facebook.react.ReactActivity { *; }
