export const STATES = [
  { id: 'lesson_ready',    title: 'Lesson Ready',           group: 'Start',    kind: 'happy' },
  { id: 'connecting',      title: 'Connecting Voice',       group: 'Start',    kind: 'happy' },
  { id: 'greeting',        title: 'Robot Greeting',         group: 'Start',    kind: 'happy' },
  { id: 'activity_intro',  title: 'Activity Intro',         group: 'Activity', kind: 'happy' },
  { id: 'robot_speaking',  title: 'Robot Speaking',         group: 'Activity', kind: 'happy' },
  { id: 'robot_listening', title: 'Robot Listening',        group: 'Activity', kind: 'happy' },
  { id: 'user_speaking',   title: 'User Speaking',          group: 'Activity', kind: 'happy' },
  { id: 'thinking',        title: 'Robot Thinking',         group: 'Activity', kind: 'happy' },
  { id: 'success',         title: 'Success Moment',         group: 'Feedback', kind: 'happy' },
  { id: 'gentle',          title: 'Gentle Correction',      group: 'Feedback', kind: 'edge'  },
  { id: 'retry',           title: 'Retry Prompt',           group: 'Feedback', kind: 'edge'  },
  { id: 'silence',         title: 'Silence Prompt',         group: 'Feedback', kind: 'happy' },
  { id: 'offtopic',        title: 'Off-topic Redirect',     group: 'Feedback', kind: 'edge'  },
  { id: 'bargein',         title: 'Interrupted (Barge-in)', group: 'Feedback', kind: 'edge'  },
  { id: 'activity_done',   title: 'Activity Complete',      group: 'Done',     kind: 'happy' },
  { id: 'lesson_done',     title: 'Lesson Complete',        group: 'Done',     kind: 'happy' },
  { id: 'reconnecting',    title: 'Reconnecting',           group: 'Edge',     kind: 'edge'  },
  { id: 'audio_error',     title: 'Audio Error',            group: 'Edge',     kind: 'edge'  },
  { id: 'safety',          title: 'Safety Fallback',        group: 'Edge',     kind: 'edge'  },
  { id: 'exit_confirm',    title: 'Exit Confirmation',      group: 'Edge',     kind: 'edge'  },
];
